### ISSUE TITLE
Problem of dialog

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/remotedev-app#13]
Currently the dialog will have following problem when I input multiline:

![2016-07-06 4 34 12](https://cloud.githubusercontent.com/assets/3001525/16612470/b8dfdcde-4399-11e6-8854-a94f3ca6ef4e.png)
It can be solved if I resize window. We can call `window.dispatchEvent(new Event('resize'))` in the `handleInputChange`, but I think it not perfect. :\

**Comment by zalmoxisus** [comment]
Seems related to https://github.com/callemall/material-ui/issues/1676
