### ISSUE TITLE
TestGen: Templates not changed if store changed to redux store

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/remotedev-app#15]
![2016-08-06 11 36 22](https://cloud.githubusercontent.com/assets/3001525/17454481/082383d4-5bca-11e6-8bc5-283bbd4447a6.png)

If I first clicked `Test` tab (not start monitoring yet), then start monitoring, it will still vanilla templates.

I think it related to [this line in constructor](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/components/TestGenerator.js#L33), so it doesn't get new templates if `store.isRedux()` changed.

**Comment by zalmoxisus** [comment]
Thanks a lot for the report!
