### ISSUE TITLE
Problems with 0.8.0-beta-2

### ISSUE THREAD

**Issue by ppershing** [zalmoxisus/remotedev-app#19]
Hi,
 current beta version deployed at npm is somehow broken-- I cannot connect to any instances of my app. This used to work with 0.7.0 version. Moreover, this breaks `remotedev-server` (and I guess remotedev.io as well) because the server loads the latest version of the app from the CDN.
Unfortunately, I don't know how to debug the problem :-(

**Comment by zalmoxisus** [comment]
Hi,
I see the problem on `remotedev-server` using `remotedev-app` from cdn, but it's since `0.4` when we starting to use `material-ui` which fails because of 2 instances of react. However, monitoring works just fine. As for http://remotedev.io/local, it uses `remotedev-app@0.7`, so if it doesn't work with it too, then the problem should be elsewhere.

Maybe updating `remote-redux-devtools` could help? If not please provide more details of your store config.

**Comment by ppershing** [comment]
As for `remotedev-server` -- If I replace CDN link with the version 0.7.0, I cannot see app instances but I am at least getting data from the active instance. When using CDN link without the explicit version, I don't see any actions at all.
As for http://remotedev.io/local -- I thought it is the same thing as chrome extension's -> "Open remote DevTools" but now I am not sure. Chrome extension does not work for me at the moment but it used to work maybe a week or two ago. I even went back in my project repo's commits and tried to hunt down the offending commit but apparently it is not working with old versions of the project as well so I started suspecting remotedev itself.
I use  `devTools({realtime: true})` in the store config

**Comment by ppershing** [comment]
Hmm, upgrading `remote-redux-devtools` to 0.4.8 seems to help so I will close the issue

**Comment by zalmoxisus** [comment]
In older versions of `remote-redux-devtools` we used to send initial state twice, but now it's not necessary.

> As for http://remotedev.io/local -- I thought it is the same thing as chrome extension's -> "Open remote DevTools" but now I am not sure.

Yes, it's the same, but I didn't published the beta there yet.

Feel free to reopen the issue if something goes wrong.

I'll try to solve the problem with umd version (cdn) before releasing. We need either to extract `react-addons-transition-group` as indicated [here](https://github.com/webpack/webpack/issues/1275#issuecomment-247684798) or remove `material-ui` (which was planned).
