### ISSUE TITLE
Error with `redux-devtools-extension`, looks like it's from `removedev-app`?

### ISSUE THREAD

**Issue by travisbt** [zalmoxisus/remotedev-app#27]
When running latest [redux-devtools](https://github.com/zalmoxisus/redux-devtools-extension) version from chrome store AND when running locally with the dev build, getting the following error.  

```javascript
Warning: Failed prop type: The prop `data` is marked as required in `JSONTree`, but its value is `undefined`.
    in JSONTree (created by StateTab)
    in StateTab (created by Tabs)
    in div (created by Tabs)
    in div (created by styled.div)
    in styled.div (created by Tabs)
    in Tabs (created by SubTabs)
    in SubTabs (created by Connect(SubTabs))
    in Connect(SubTabs) (created by ActionPreview)
    in div (created by ActionPreview)
    in div (created by ActionPreview)
    in ActionPreview (created by DevtoolsInspector)
    in div (created by DevtoolsInspector)
    in DevtoolsInspector (created by InspectorWrapper)
    in InspectorWrapper (created by DevTools)
    in DevTools (created by App)
    in div (created by App)
    in App (created by _class2)
    in MuiThemeProvider (created by _class2)
    in _class2 (created by Connect(_class2))
    in Connect(_class2)
    in Provider
```

**Comment by travisbt** [comment]
@zalmoxisus The way this `shows` in the devtools ext, is that clicking on `Diff`, `State`, `Raw` etc all are undefined and their respective rendered apps do not change.  

If I load up `my` application, fire off lots of events and THEN open redux-devtool-ext, everything looks great. But, after opening the extension UI, if I go into `my` app and fire off more actions, then the above error is thrown and the `Diff`, `State` etc are broken as `undefined`.

**Comment by zalmoxisus** [comment]
The first part is indeed confusing, probably we'll have just a message when there's no data. When you first time open the extension it's expected to have no data, and to have the state and action as `undefined`. We should remove that warning (remove `isRequered` from `data` prop in Inspector monitor component).

Are you able to replicate the issue in the second part (loosing the state) with [our example](http://zalmoxisus.github.io/examples/counter/)?

**Comment by travisbt** [comment]
Everything is working great after I open the extension.  I can browse all the previous actions, and all the `Diff`, `Raw`, `State` etc are looking great. Then, if I fire off more actions with the extension actually `open`, I get the mentioned error for ALL actions,  old and new.

**Comment by travisbt** [comment]
@zalmoxisus I'm not able to reproduce the issue with [the example](http://zalmoxisus.github.io/examples/counter/).

Have you experienced the above issue before?  Any fix, I could test myself locally.

**Comment by travisbt** [comment]
Let me add this.  We're adding react modules to a page in different locations, not a SPA yet.  Here's the redux part of our main.js

```javascript

const { store } = createReduxStore();

render(
  <Provider store={store}>
    <NotesComponent />
  </Provider>,
  document.getElementById('Notes')
);

render(
  <Provider store={store}>
    <TodosComponent />
  </Provider>,
  document.getElementById('Todos')
);
```

We did this so we can segment the code base, and drop the new mini-apps in different locations on the page AND still have them share a redux store.  This is working great in the app.  I'm only seeing errors in the extension as described above.

**Comment by zalmoxisus** [comment]
No, I didn't get such issues before. Passing the store to the Provider component doesn't affect the extension.

When you loose the state, do you have any instances in the extension's select box (where `Autoselect instance` is by default)? Does this happen all the time you dispatch those actions?

**Comment by travisbt** [comment]
Testing again, and the first error in the extension is below.

```javascript
Warning: Failed prop type: Invalid prop `computedStates` of type `object` supplied to `DevtoolsInspector`, expected `array`.
    in DevtoolsInspector (created by InspectorWrapper)
    in InspectorWrapper (created by DevTools)
    in DevTools (created by App)
    in div (created by App)
    in App (created by _class2)
    in MuiThemeProvider (created by _class2)
    in _class2 (created by Connect(_class2))
    in Connect(_class2)
    in Provider
```

After clicking a few more actions, I get the one at the top of this issue.

**Comment by travisbt** [comment]
Also: After I start clicking in my app to dispatch other actions, I still see ALL the actions, old and new. BUT, now, their `Diff`, `State` and `Raw` tabs look like this.

```javascript
  (pin): undefined
```

So I can see the actions on the left, and when I click the `Action` tab.  But all the other tabs are failing.

Seems like something is failing when trying to get the newly updated state.  So then the `State` view and the `Diff` view are blowing up, and stay that way.

**Comment by zalmoxisus** [comment]
`computedStates` is modified only in [here](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/reducers/instances.js) and [here](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/utils/updateState.js), and I don't see how it can become an object unless it received an object instead of an array. Another scenario could be that it passes anything else to the components.

It would be difficult for me to find the problem without a minimal repo to reproduce the issue.

You could run `remotedev-app` as a web app. So you can investigate those parts. Just do `npm i && npm start` or `yarn && yarn start` (the latter will guarantee that you have the same dependencies as I have). To pass data from you app you'll have to add [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools) enhancer to your app instead the extension's one. By default it uses `remotedev.io` server as a bridge to be simple to start, but you can also install [`remotedev-server`](https://github.com/zalmoxisus/remotedev-server).

At least we'll know if the problem is here or in the extension's injected script.

**Comment by travisbt** [comment]
In the instance I'm looking at now, one of the actions flowing through the devtools has `action.request.payload.computedStates` as an object.  All the ones that follow are an array.

**Comment by travisbt** [comment]
Appears that this is erroring the Slider component among others.

**Comment by travisbt** [comment]
```javascript
 wsSocket.onmessage = function (message, flags) {
    self._onMessage(message.data); // ..payload.computedStates is an Object
 };
```

In that code, running `JSON.parse(JSON.parse(message.data).data.data.payload);` to look at the actual message, shows the `computedStates` as an `object`.

**Comment by travisbt** [comment]
Also, I'm running the `remotedev-server`, `remotedev-app` and have updated my app to use the `composeWithDevTools({ realtime: true, port: 8000 });` which is pointing to the server.

**Comment by travisbt** [comment]
From debugging the `composeWithDevTools` the `computedStates` appears to be `sent` as an Array. I'll investigate the `remotedev-server` to see what it's doing now.

**Comment by zalmoxisus** [comment]
Thanks for investigating this. Do you have any clue of how it could become an object, after being sent as an array? What's the value exactly of `computedStates`?

**Comment by travisbt** [comment]
The object it's returning is looks like an Array converted to an object. The keys in the object are index numbers. Ex. `{ 0 : { ..... }, 1: { .... }, 2: { .... } }`.   I'll check how many events are getting sent in this object now.

Is there a known limit to the amount of actions that are passed up front?

**Comment by travisbt** [comment]
Object only has 2 elements in it. `{ 0: { ... }, 1: { ... } }`.

**Comment by zalmoxisus** [comment]
> Is there a known limit to the amount of actions that are passed up front?

The default limit is `30` for Remote Redux DevTools and `50` for the extension. When it's exceeded the first action is removed. I thought that could be the issue, but it's not.

**Comment by zalmoxisus** [comment]
Well, from https://github.com/zalmoxisus/remotedev-app/issues/27#issuecomment-269387877 we know that `computedStates` is spoiled before reaching `remotedev-app`. Could you please check if in your app `store.liftedStore.getState()` has the same problem?

**Comment by travisbt** [comment]
Currently, the below is always an __array__ in the `devTools` code for `getLiftedState()`
```javascript
   store.liftedStore.getState().computedStates // Array []
```
Any other places to look @zalmoxisus ?

**Comment by zalmoxisus** [comment]
I'm a bit confused about https://github.com/zalmoxisus/remotedev-app/issues/27#issuecomment-269387877.


There are 2 places to check when that issue occurs:
1. If the sent message is ok [here](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/src/devTools.js#L83) or received request is ok [here](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/middlewares/api.js#L84).
2. If the transformed state is ok [here](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/reducers/instances.js#L122).

**Comment by travisbt** [comment]
Looks like it's leaving my app in the correct state. However, as soon as I gets the message in the `removedev-app`, it's already an object.  So looks like the issue is not in the code for `remotedev-app` and not in the `devTools` compose function.

**Comment by travisbt** [comment]
@zalmoxisus Is there someplace further up the tool chain to check in `remotedev-app` or `devTools`?

**Comment by zalmoxisus** [comment]
@travisbt, you can debug `remotedev-app` with Redux DevTools Extension. It is already included in the development mode when you do `npm start`. So you can see how the instances state is changing. You should be able even to generate a ready test for that issue right from the extension.

**Comment by zalmoxisus** [comment]
I missed the previous message. So the received `request` is already altered? Then we should investigate what is happening in [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/src/devTools.js#L83). It cannot be altered in any way in `remotedev-server`.

**Comment by travisbt** [comment]
Gotcha!  I'll keep debugging the devTools and see what else is being done.

**Comment by travisbt** [comment]
I found the problem! We have a `core-js` polyfill that is used by Babeljs on our page (for other reasons) and it was corrupting the `JSON.stringify()` function in the `relay()` method in `devTools`.

So when setting `message.payload = ... JSON.stringify(state)`, was turning the array into an object.  

In my previous debugging, I was testing the value right before it was sent to the method to be packaged and sent off.  

@zalmoxisus Thanks for your awesome help!  The tools you've created are amazing!

**Comment by zalmoxisus** [comment]
That was hard indeed to spot. Thank you for all the investigation!

Maybe we still have to go further and see why it causes this issue? You mean the official [`core-js`](https://github.com/zloirock/core-js)? Maybe that's an issue with [`jsan`](https://github.com/kolodny/jsan) (which we're using for stringifying)?

**Comment by travisbt** [comment]
Ahh! I didn't notice the diff there!  

We were importing the `core-js` library as a `<script>`.  The page in question is not a single page app, so we're mixing some React with other tools on the page, that already have various polyfills.  Thus we needed to add the `core-js` library for IE support.  Removing it from the page `fixed` the issue.  

However, since you pointed out the different library, I'd like to take a look at that as well!  I'll let you know if I can pin-point the issue.
