### ISSUE TITLE
remotedev.io not running latest version of remotedev-app ?

### ISSUE THREAD

**Issue by gcox** [zalmoxisus/remotedev-app#28]
The slider doesn't appear to get any styles applied to it when running via remotedev.io. If I pull down the latest remotedev-app code and run it locally, the slider is styled as expected.  Is the remotedev.io site not running the latest version?

**Comment by zalmoxisus** [comment]
Good catch. That's just because the page's background wss white there. Fixed that, and will publish a new version soon.

**Comment by PoignardAzur** [comment]
Should this issue be closed?
