### ISSUE TITLE
Option to customize export file name

### ISSUE THREAD

**Issue by minedeljkovic** [zalmoxisus/remotedev-app#29]
I think it would be nice to add option for customizing export file name. Currently it is hardcoded [here](https://github.com/zalmoxisus/remotedev-app/blob/139a6258be5780ca55c38c94590114490ba69381/src/app/middlewares/exportState.js#L11).

For example it could be a setting named `exportFileName` in [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md). Or current `export` [feature setting](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#features) could optionally be an object with `fileName` prop.
One of the values can be a function that returns the name of the file. I would, for example, use it to put timestamp and app version in file name.

I would happily issue PR, but I cannot quite understand how are options propagated from [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) to [here](https://github.com/zalmoxisus/remotedev-app/blob/139a6258be5780ca55c38c94590114490ba69381/src/app/middlewares/exportState.js).

**Comment by zalmoxisus** [comment]
@minedeljkovic in Redux Extension 3.0 (and Remotedev App 0.11) we'll have reports. So, except the saved history, you'll have the information about [when it was saved, title, description...] (https://github.com/zalmoxisus/remotedev-server/blob/v0.3/lib/store.js#L45-L60). Moreover you'll be able to create custom monitors for dealing with reports as we do now for actions. Reports can be also shared with your team as you do with files. I think it would better fit this issue than adding information in the file name. 

For now, in Chrome settings, click `Show advanced settings`, then search for `Downloads` section and click  `Ask where to save each file before downloading`. Then when saving a file you can chose the name (`state.json` will be just a suggestion). We can add this in FAQ.

If you still think that the suggested option has some advantages, we send it from [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L216-L220), then [include in the state](https://github.com/zalmoxisus/remotedev-app/blob/master/src/app/reducers/instances.js#L206-L217). Then [like we're accessing `options.features.export`](https://github.com/zalmoxisus/remotedev-app/blob/139a6258be5780ca55c38c94590114490ba69381/src/app/middlewares/exportState.js#L37) , we could use an additional option.

The problem, however, is if you don't want to use a constant for `exportFileName` option, but a function, which is not serializable. So, we should call that function [on the client part](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L69-L80), include the result in the object passing to `toContentScript`, and then access it from [here](https://github.com/zalmoxisus/remotedev-app/blob/139a6258be5780ca55c38c94590114490ba69381/src/app/middlewares/exportState.js#L29-L31) as `request.fileName`.

**Comment by minedeljkovic** [comment]
Thanks, @zalmoxisus for a very detailed answer!
It seems reasonable to wait and see how reports are going to work, so I will close this.

I might, though, issue a PR if this would have its use case aside reports, since you already pretty much specified the design of solution. :)
