### ISSUE TITLE
remotedev-app@0.10.7/dist/remotedev-app.min.js is not latest build?

### ISSUE THREAD

**Issue by jkzing** [zalmoxisus/remotedev-app#31]
I was trying to embed remotedev-app into vscode. With limitation of vscode extension api, I need to use pure html to open remotedev-app.

When importing remotedev-app with a script tag from `https://unpkg.com/remotedev-app@0.10.7/dist/remotedev-app.min.js`, the tap event is broken. All material-ui related component can not handle tap event correctly. eg. MonitorSelector, Settings dialog

I tried to folk the source, run `npm run build:web` myself, and import the build result `app.bundle.js` into html. It works totally fine.

I'm supposing maybe `remotedev-app.min.js` is not latest build? Could you please help to check that?

BTW, here is the [fiddle](https://jsfiddle.net/jingkaizhao/g00dgqdf/).

**Comment by zalmoxisus** [comment]
Could you please try https://unpkg.com/remotedev-app@0.11.0-0/dist/remotedev-app.min.js? It doesn't contains material-ui, and thus no need for tap event which was causing troubles in the umd build.

**Comment by jkzing** [comment]
Um...it seems version 0.11.0 build still has issues. 
I tried to update my [fiddle](https://jsfiddle.net/jingkaizhao/g00dgqdf/2/), and it's not working.

There is a React exception:
```
Uncaught Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (react-dom.min.js:15)
    at p.i [as _instantiateReactComponent] (react-dom.min.js:15)
    at performInitialMount (react-dom.min.js:13)
    at p.mountComponent (react-dom.min.js:13)
    at Object.mountComponent (react-dom.min.js:14)
    at a (react-dom.min.js:14)
    at r.perform (react-dom.min.js:15)
    at s (react-dom.min.js:14)
    at r.perform (react-dom.min.js:15)
    at Object.batchedUpdates (react-dom.min.js:14)
```

I can not get the not minified version work, thus don't have an idea on it.

**Comment by zalmoxisus** [comment]
The current umd build includes React-Dom rendering. By removing your script, I got it work: https://jsfiddle.net/9xpwmghd/

However, I guess we should use `./src/index.js` as entry point [here](https://github.com/zalmoxisus/remotedev-app/blob/new-ui/webpack.config.umd.js#L7), so it will work as you expected.

**Comment by zalmoxisus** [comment]
I fixed that in `0.11.0-1`: https://jsfiddle.net/5fzmxwqj/

Note that it's still alpha, and some new features (like persisting and saving report) aren't implemented yet.

**Comment by jkzing** [comment]
Looks awesome! I'll temporarily use `0.11.0-2` build until the official release.

Thanks and look forward for the release!

**Comment by jkzing** [comment]
PS: here is the vscode extension:

[https://marketplace.visualstudio.com/items?itemName=jingkaizhao.vscode-redux-devtools](https://marketplace.visualstudio.com/items?itemName=jingkaizhao.vscode-redux-devtools)

and the repo:

[https://github.com/jkzing/vscode-redux-devtools](https://github.com/jkzing/vscode-redux-devtools)

**Comment by zalmoxisus** [comment]
@jkzing well done. The slider will look better when we have https://github.com/calesce/redux-slider-monitor/pull/26 merged.

Feel free to send a pr to add a link here and to ['remote-redux-devtools'](https://github.com/zalmoxisus/remote-redux-devtools) in the README along.
